### ISSUE TITLE
SQL Error after adding/changing User Profile Picture

### ISSUE THREAD

**Issue by PyroJayxX** [chaotic-braindead/Enrollment#6] opened 2024-01-08 07:18 UTC
When changing/adding profile picture of **Student** and **Admin**, the following error occurs when you try to re-login them again,

![image](https://github.com/chaotic-braindead/Enrollment/assets/113975518/69aa8eaf-f046-4ca9-b190-175053f928c0)

I reckon the database connection somehow closes when the user has an embedded user picture.

**Comment by chaotic-braindead** [comment] 2024-01-08 08:06
I believe the error was caused by the Java garbage collector which deemed the Connection instance unused upon login. Should be fixed by the next commit, though. Thanks


Connecting to the database is now a static method that returns a new instance of a Connection every time.
``` 
public static Connection connect(){
        Connection conn = null;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/"+DB,
                    "oop",
                    "oop");
        } catch(Exception e) {
            AlertMessage.showInformationAlert("An error occurred while connecting to database: " + e);
        }
        return conn;
    } ... and so on...
```

**Closed as completed** 2024-01-08 09:41 UTC
Labels: bug
